# -*- coding: utf-8 -*-
"""
  run_parameters_init.py generated by WhatsOpt 1.6.1
"""
import numpy as np

def initialize(mda):

    mda['Ae'] = 1.5926
    mda['beta'] = 1.0
    mda['De'] = 1.424
    mda['Ds'] = 1.27
    mda['Dt'] = 1.0
    mda['FF'] = 0.95
    mda['g0'] = 9.80665 
    mda['gamma'] = 1.22
    mda['k_sm'] = 1
    mda['L_vehicle'] = 1.0
    mda['M_case'] = 1.0
    mda['M_igniter'] = 1.0
    mda['M_nozzle'] = 1.0
    mda['M_PL'] = 140
    mda['Pa'] = 26442
    mda['Pc'] =  5610000
    mda['Pe'] = 18327
    mda['R'] = 286.689655
    mda['rho_p'] = 1.0
    mda['Ru'] = 1.0
    mda['SF'] = 0.03
    mda['S_int'] = 1.0
    mda['tb'] = 1.0
    mda['Tc'] = 75.3
    mda['theta_n'] = 1.0
    mda['zeta'] = 0.93630 



if __name__ == "__main__":
    from tabulate import tabulate

    mda = {}
    initialize(mda)
    headers = ["parameter", "value"]
    data = [[k, mda[k]] for k in mda]
    print(tabulate(data, headers))