# -*- coding: utf-8 -*-
"""
  length_convergent_section_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 79

import numpy as np
from openmdao.api import ExplicitComponent

class LengthConvergentSectionBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate LengthConvergentSection discipline """

    def setup(self):
        self.add_input('beta', val=1.0, desc='Nozzle convergent half angle')
        self.add_input('Ds', val=1.27, desc='Stage diameter')
        self.add_input('Dt', val=1.0, desc='Nozzle throat diameter')

        self.add_output('L_conv', val=np.ones((1,)), desc='Convergent nozzle section length')



        