# -*- coding: utf-8 -*-
"""
  length_divergent_section_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 79

import numpy as np
from openmdao.api import ExplicitComponent

class LengthDivergentSectionBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate LengthDivergentSection discipline """

    def setup(self):
        self.add_input('De', val=1.424, desc='Nozzle exit diameter')
        self.add_input('Dt', val=1.0, desc='Nozzle throat diameter')
        self.add_input('Ru', val=1.0, desc='Longitudinal radius of the throat')
        self.add_input('theta_n', val=1.0, desc='Nozzle divergent half angle')

        self.add_output('L_div', val=np.ones((1,)), desc='Divergent nozzle section length')



        