# -*- coding: utf-8 -*-
"""
  propellants_mass_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 79

import numpy as np
from openmdao.api import ExplicitComponent

class PropellantsMassBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate PropellantsMass discipline """

    def setup(self):
        self.add_input('prop_m', val=1.0, desc='Propellantmass flow rate')
        self.add_input('SF', val=0.03, desc='Sliver fraction')
        self.add_input('tb', val=1.0, desc='Burn time')

        self.add_output('Mp', val=np.ones((1,)), desc='')



        