# -*- coding: utf-8 -*-
"""
  solid_rocket_length_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 79

import numpy as np
from openmdao.api import ExplicitComponent

class SolidRocketLengthBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate SolidRocketLength discipline """

    def setup(self):
        self.add_input('L_case', val=np.ones((1,)), desc='')
        self.add_input('L_conv', val=np.ones((1,)), desc='Convergent nozzle section length')
        self.add_input('L_div', val=np.ones((1,)), desc='Divergent nozzle section length')

        self.add_output('L_SRM', val=np.ones((1,)), desc='Length of a solid rocket stage')



        