# -*- coding: utf-8 -*-
"""
  solid_rocket_mass_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 79

import numpy as np
from openmdao.api import ExplicitComponent

class SolidRocketMassBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate SolidRocketMass discipline """

    def setup(self):
        self.add_input('Mp', val=np.ones((1,)), desc='')
        self.add_input('M_case', val=1.0, desc='')
        self.add_input('M_igniter', val=1.0, desc='')
        self.add_input('M_nozzle', val=1.0, desc='')

        self.add_output('M_SRM', val=np.ones((1,)), desc='Mass of a solid rocket stage')



        