# -*- coding: utf-8 -*-
"""
  solid_motor_length.py generated by WhatsOpt 1.6.1
"""
import numpy as np
from solid.solid_motor_length_base import SolidMotorLengthBase

class SolidMotorLength(SolidMotorLengthBase):
    """ An OpenMDAO component to encapsulate SolidMotorLength discipline """
		
    def compute(self, inputs, outputs):
        """ SolidMotorLength computation """
    
        outputs['L_case'] = np.ones((1,))   

# Reminder: inputs of compute()
#   
#       inputs['Ds'] -> shape: (1,), type: Float    
#       inputs['FF'] -> shape: (1,), type: Float    
#       inputs['Mp'] -> shape: (1,), type: Float    
#       inputs['rho_p'] -> shape: (1,), type: Float      
	
# To declare partial derivatives computation ...
# 
#    def setup(self):
#        super(SolidMotorLength, self).setup()
#        self.declare_partials('*', '*')  
#			
#    def compute_partials(self, inputs, partials):
#        """ Jacobian for SolidMotorLength """
#   
#       	partials['L_case', 'Ds'] = np.zeros((1, 1))
#       	partials['L_case', 'FF'] = np.zeros((1, 1))
#       	partials['L_case', 'Mp'] = np.zeros((1, 1))
#       	partials['L_case', 'rho_p'] = np.zeros((1, 1))        
