# -*- coding: utf-8 -*-
"""
  fairing_mass_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 80

import numpy as np
from openmdao.api import ExplicitComponent

class FairingMassBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate FairingMass discipline """

    def setup(self):
        self.add_input('Ds', val=1.27, desc='Stage diameter')
        self.add_input('L_fairing', val=np.ones((1,)), desc='')

        self.add_output('M_fairing', val=np.ones((1,)), desc='Fairing mass')



        