# -*- coding: utf-8 -*-
"""
  payload_adapter_mass_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 80

import numpy as np
from openmdao.api import ExplicitComponent

class PayloadAdapterMassBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate PayloadAdapterMass discipline """

    def setup(self):
        self.add_input('M_PL', val=140, desc='Payloadmass')

        self.add_output('M_PLA', val=np.ones((1,)), desc='Payload adapter mass')



        