# -*- coding: utf-8 -*-
"""
  power_subsystem_mass_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 80

import numpy as np
from openmdao.api import ExplicitComponent

class PowerSubsystemMassBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate PowerSubsystemMass discipline """

    def setup(self):
        self.add_input('M_avionics', val=np.ones((1,)), desc='')

        self.add_output('M_EPS', val=np.ones((1,)), desc='Power subsystemmass')



        