# -*- coding: utf-8 -*-
"""
  fonction_vandenkerckhove_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 78

import numpy as np
from openmdao.api import ExplicitComponent

class FonctionVandenkerckhoveBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate FonctionVandenkerckhove discipline """

    def setup(self):
        self.add_input('gamma', val=1.22, desc='Flight path angle')

        self.add_output('gamma_maj', val=np.ones((1,)), desc='Vandenkerckhove function')



        