# -*- coding: utf-8 -*-
"""
  characteristic_velocity_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 78

import numpy as np
from openmdao.api import ExplicitComponent

class CharacteristicVelocityBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate CharacteristicVelocity discipline """

    def setup(self):
        self.add_input('gamma_maj', val=np.ones((1,)), desc='Vandenkerckhove function')
        self.add_input('R', val=286.689655, desc='Specific gas constant')
        self.add_input('Tc', val=75.3, desc='Combustion chamber temperature')

        self.add_output('C_star', val=np.ones((1,)), desc='Characteristic velocity')



        