# -*- coding: utf-8 -*-
"""
  exhaust_velocity_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 78

import numpy as np
from openmdao.api import ExplicitComponent

class ExhaustVelocityBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate ExhaustVelocity discipline """

    def setup(self):
        self.add_input('C_F', val=np.ones((1,)), desc='Thrust coefficient')
        self.add_input('C_star', val=np.ones((1,)), desc='Characteristic velocity')

        self.add_output('Ve', val=np.ones((1,)), desc='Exhaust gas true exhaust velocity')



        