# -*- coding: utf-8 -*-
"""
  specific_impulse_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 78

import numpy as np
from openmdao.api import ExplicitComponent

class SpecificImpulseBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate SpecificImpulse discipline """

    def setup(self):
        self.add_input('g0', val=9.80665, desc='Earth’s gravitational acceleration at sea level')
        self.add_input('Ve', val=np.ones((1,)), desc='Exhaust gas true exhaust velocity')

        self.add_output('Isp', val=np.ones((1,)), desc='Specific impulse')



        