# -*- coding: utf-8 -*-
"""
  throat_area_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 78

import numpy as np
from openmdao.api import ExplicitComponent

class ThroatAreaBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate ThroatArea discipline """

    def setup(self):
        self.add_input('Ae', val=1.5926, desc='Nozzle exit area')
        self.add_input('epsilon', val=np.ones((1,)), desc='Expansion ratio')

        self.add_output('At', val=np.ones((1,)), desc='Throat area')



        