# -*- coding: utf-8 -*-
"""
  thrust_coefficient_base.py generated by WhatsOpt 1.6.1
"""
# DO NOT EDIT unless you know what you are doing
# whatsopt_url: 
# analysis_id: 78

import numpy as np
from openmdao.api import ExplicitComponent

class ThrustCoefficientBase(ExplicitComponent):
    """ An OpenMDAO base component to encapsulate ThrustCoefficient discipline """

    def setup(self):
        self.add_input('gamma', val=1.22, desc='Flight path angle')
        self.add_input('gamma_maj', val=np.ones((1,)), desc='Vandenkerckhove function')
        self.add_input('Pc', val= 5610000, desc='Combustion chamber pressure')
        self.add_input('Pe', val=18327, desc='Nozzle exit pressure')

        self.add_output('C_F', val=np.ones((1,)), desc='Thrust coefficient')



        